
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;
import javax.swing.JButton;

public class user_home extends javax.swing.JFrame {
  int x = 10, y = 10;
    public user_home(String email) {
        initComponents();
        setSize(600, 500);
        lb.setText("Welcome"+" "+email);
        loadcategory();
    }

     void loadcategory() {
       
        String ans = myClient.fetchcat();

        StringTokenizer st = new StringTokenizer(ans, ";;");

        int n = st.countTokens();

        JButton arr[] = new JButton[n];

        for (int i = 0; i < n; i++) {

            String row = st.nextToken();

            StringTokenizer st1 = new StringTokenizer(row, "$");

            String name = st1.nextToken();
            String photo = st1.nextToken();

            arr[i] = new JButton(name);

            ImageIcon ic = new ImageIcon(photo);
            Image img = ic.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
            ImageIcon ic1 = new ImageIcon(img);

            arr[i].setIcon(ic1);

            arr[i].setBounds(x, y, 200, 100);
            
            arr[i].addActionListener(new ActionListener(){
            
            @Override
            public void actionPerformed(ActionEvent e)
            {
                //open next frame
                courses obj = new courses(name);
                obj.setVisible(true);
                dispose();
            }
            
            });
 
            if (x < 210) 
            {
                
                x = x + 200;
                System.out.println("-->"+x);
                System.out.println("-->"+name);
            } 
            else {
                System.out.println("--+"+x);
                 System.out.println("-->"+name);
                x = 10;
                y = y + 100;
            }
            
                mainpanel.add(arr[i]);
            mainpanel.repaint();

        }
        
        mainpanel.setPreferredSize(new Dimension(420, y + 100));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mainpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(lb);
        lb.setBounds(0, 0, 500, 70);

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(mainpanel);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(50, 80, 490, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_home("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb;
    private javax.swing.JPanel mainpanel;
    // End of variables declaration//GEN-END:variables
}
